CREATE TABLE tipo_cultura (
    id_cultura NUMBER PRIMARY KEY,
    nome VARCHAR2(50),
    data_plantio DATE
);

CREATE TABLE area_cultivo (
    id_area NUMBER PRIMARY KEY,
    id_cultura NUMBER,
    area_extensao NUMBER(10, 2),
    end_localizacao VARCHAR2(100),
    FOREIGN KEY (id_cultura) REFERENCES tipo_cultura(id_cultura)
);

CREATE TABLE sensor (
    id_sensor NUMBER PRIMARY KEY,
    id_area NUMBER,
    descricao VARCHAR2(100),
    tipo VARCHAR2(50),
    modelo VARCHAR2(50),
    FOREIGN KEY (id_area) REFERENCES area_cultivo(id_area)
);

CREATE TABLE leituras (
    id_leitura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    temp NUMBER(5, 2),
    humid NUMBER(5, 2),
    P VARCHAR2(20),
    K VARCHAR2(20),
    pH NUMBER(5, 2),
    estado_irrigacao VARCHAR2(20),
    motivo_irrigacao VARCHAR2(255),
    id_sensor NUMBER,
    FOREIGN KEY (id_sensor) REFERENCES sensor(id_sensor)
);

CREATE TABLE previsoes_irrigacao (
    id_previsao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp_previsao TIMESTAMP,
    estado_irrigacao_previsto VARCHAR2(20),
    probabilidade NUMBER(5, 2),
    data_geracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
